spring:
  application:
    name: "auth-server"
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: "aventica"
    password: "aventica"
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: classpath:secret/google_client_id.txt
            client-secret: classpath:secret/google_client_secret.txt
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  session:
    jdbc:
      table-name: SPRING_SESSION
    timeout: 10m

station:
  config:
    auth-server: # TODO: use env variables
      password-prefix: "{bcrypt}"
      rsa-public-key: classpath:secret/public.pem
      rsa-private-key: classpath:secret/private.pem

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

logging:
  level:
    org:
      springframework:
        security: TRACE
    dev:
      aventix: TRACE