spring:
  application:
    name: "auth-server"
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liQKGMY4YHaZVfEs
            client-secret: e96263017c02351e2b153c7e7fa84f1142e56965
            scope: user:email
            redirect-uri: "http://localhost:8090/v1/auth/login/oauth2/callback/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

station:
  config:
    auth-server: # TODO: use env variables
      password-prefix: "{bcrypt}"
      rsa-public-key: classpath:rsa/public.pem
      rsa-private-key: classpath:rsa/private.pem

server:
  port: 8090