spring:
  application:
    name: "auth-server"
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.cakmak-station.de
      client:
        registration:
          google:
            provider: google
            client-id: ${STATION_GOOGLE_CLIENT_ID}
            client-secret: ${STATION_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  session:
    jdbc:
      table-name: SPRING_SESSION
    timeout: 10m

station:
  config:
    auth-server: # TODO: use env variables
      password-prefix: "{bcrypt}"
      rsa-public-key: classpath:secret/public.pem
      rsa-private-key: classpath:secret/private.pem

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

logging:
  level:
    org:
      springframework:
        security: TRACE
    dev:
      aventix: TRACE