spring:
  application:
    name: "auth-server"
  jpa:
    hibernate:
      ddl-auto: update



station:
  config:
    auth-server: # TODO: use env variables
      rsa-public-key: classpath:rsa/public.pem
      rsa-private-key: classpath:rsa/private.pem