spring:
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          # Point to the standard JWK Set endpoint provided by Spring Authorization Server
          jwk-set-uri: http://localhost:8081/oauth2/jwks
  application:
    name: Station-Guide
server:
  port: 8082
