spring:
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  application:
    name: Station-Guide
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: TRACE
