<script setup lang="ts">
import { ref, reactive, defineEmits } from 'vue';
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import EmployeeService, { Employee, Account, EmployeeAddress } from "@/service/EmployeeService"; // Import necessary interfaces

const emit = defineEmits(['close', 'employee-created']);

// Reactive object now includes fields for both Employee and Account creation
const newEmployee = reactive({
  // Account fields
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  // Employee specific fields
  address: {
    zipcode: null as number | null,
    city: '',
    street: '',
    streetNumber: '',
    apartment: ''
  },
  birthDate: null as Date | null, // Added - Use YYYY-MM-DD format from date input
  taxId: null as number | null, // Added
  socialSecurityId: '', // Added
  minijob: false,
  hourlyWage: null as number | null,
});

const isLoading = ref(false);
const errorMessage = ref('');
const successMessage = ref('');

// Enhanced validation
const validateForm = () => {
  errorMessage.value = '';
  if (!newEmployee.firstName) {
    errorMessage.value = 'Vorname ist erforderlich.'; return false;
  }
  if (!newEmployee.lastName) {
    errorMessage.value = 'Nachname ist erforderlich.'; return false;
  }
  if (!newEmployee.email || !/\S+@\S+\.\S+/.test(newEmployee.email)) {
    errorMessage.value = 'Gültige E-Mail ist erforderlich.'; return false;
  }
  if (!newEmployee.password || newEmployee.password.length < 8) {
    errorMessage.value = 'Passwort muss mindestens 8 Zeichen lang sein.'; return false;
  }
  // Address validation
  if (!newEmployee.address.zipcode) {
      errorMessage.value = 'Postleitzahl ist erforderlich.'; return false;
  }
  if (!newEmployee.address.city) {
      errorMessage.value = 'Stadt ist erforderlich.'; return false;
  }
  if (!newEmployee.address.street) {
      errorMessage.value = 'Straße ist erforderlich.'; return false;
  }
  if (!newEmployee.address.streetNumber) {
      errorMessage.value = 'Hausnummer ist erforderlich.'; return false;
  }
  // Birth Date validation
  if (!newEmployee.birthDate) {
      errorMessage.value = 'Geburtsdatum ist erforderlich.'; return false;
  }
  // Tax ID validation
  if (newEmployee.taxId === null || newEmployee.taxId <= 0) { // Basic check, adjust regex/logic as needed
      errorMessage.value = 'Steuer-ID ist erforderlich.'; return false;
  }
  // Social Security ID validation
  if (!newEmployee.socialSecurityId) { // Basic check, adjust regex/logic as needed
      errorMessage.value = 'Sozialversicherungsnummer ist erforderlich.'; return false;
  }
  // Hourly wage validation if not a minijob
  if (!newEmployee.minijob && (newEmployee.hourlyWage === null || newEmployee.hourlyWage <= 0)) {
      errorMessage.value = 'Stundenlohn ist erforderlich (außer bei Minijob).'; return false;
  }

  return true;
};

const createEmployee = async () => {
  if (!validateForm()) {
    return;
  }

  isLoading.value = true;
  errorMessage.value = '';
  successMessage.value = '';

  try {
    // Construct the Employee payload (excluding fields generated by backend like id, badgeNumber)
    // Note: We cast the address part to EmployeeAddress to satisfy the type.
    const employeePayload: Omit<Employee, 'id' | 'badgeNumber'> = {
        firstName: newEmployee.firstName,
        lastName: newEmployee.lastName,
        email: newEmployee.email,
        address: {
            zipcode: newEmployee.address.zipcode!, // Use non-null assertion as it's validated
            city: newEmployee.address.city,
            street: newEmployee.address.street,
            streetNumber: newEmployee.address.streetNumber,
            apartment: newEmployee.address.apartment || undefined // Send undefined if empty
        } as EmployeeAddress,
        birthDate: newEmployee.birthDate, // Already in YYYY-MM-DD format from input type="date"
        taxId: newEmployee.taxId!, // Use non-null assertion as it's validated
        socialSecurityId: newEmployee.socialSecurityId,
        minijob: newEmployee.minijob,
        hourlyWage: newEmployee.hourlyWage ?? undefined, // Send undefined if null
    };
    console.log("Creating employee. Tax id emp payload: " + employeePayload.taxId)

    // Construct the Account payload (excluding fields generated/set by backend like id, badgeNumber, authorities)
    const accountPayload: Omit<Account, 'id' | 'badgeNumber' | 'authorities'> = {
        firstName: newEmployee.firstName,
        lastName: newEmployee.lastName,
        email: newEmployee.email,
        password: newEmployee.password, // Include password for account creation
        authorities: []
    };


    // Call the service function with both payloads
    // We cast the payloads to the full types, assuming the service/backend handles missing IDs etc.
    await EmployeeService.createEmployee(employeePayload as Employee, accountPayload as Account);

    successMessage.value = 'Mitarbeiter erfolgreich erstellt!';
    isLoading.value = false;

    // Optionally reset form
    newEmployee.firstName = '';
    newEmployee.lastName = '';
    newEmployee.email = '';
    newEmployee.password = '';
    newEmployee.address = { zipcode: null, city: '', street: '', streetNumber: '', apartment: '' };
    newEmployee.birthDate = null;
    newEmployee.taxId = null;
    newEmployee.socialSecurityId = '';
    newEmployee.minijob = false;
    newEmployee.hourlyWage = null;


    emit('employee-created'); // Notify parent
    setTimeout(() => {
        closeDialog(); // Close after a short delay
    }, 1500); // Close after 1.5 seconds

  } catch (error: any) {
    console.error("Error creating employee:", error);
    errorMessage.value = `Fehler beim Erstellen des Mitarbeiters: ${error.response?.data?.message || error.message || 'Unbekannter Fehler'}`;
    isLoading.value = false;
  }
};

const closeDialog = () => {
  // Reset state if needed before closing
  errorMessage.value = '';
  successMessage.value = '';
  isLoading.value = false;
  emit('close');
};
</script>

<template>
  <div :class="$style['modal-overlay']">
    <div :class="$style['modal-content']">
      <div :class="$style['modal-header']">
        <h2>Neuen Mitarbeiter anlegen</h2>
        <button @click="closeDialog" :class="$style['close-button']" aria-label="Schließen">
          <FontAwesomeIcon icon="times"/>
        </button>
      </div>
      <div :class="$style['modal-body']">
        <form @submit.prevent="createEmployee">
          <!-- Personal & Account Info -->
          <h3 :class="$style['section-title']">Persönliche Daten & Account</h3>
          <div :class="$style['grid-layout']">
            <div :class="$style['form-group']">
              <label for="employee-firstname">Vorname <span :class="$style['required']">*</span></label>
              <input type="text" id="employee-firstname" v-model="newEmployee.firstName" :class="$style['input']" required :disabled="isLoading"/>
            </div>
            <div :class="$style['form-group']">
              <label for="employee-lastname">Nachname <span :class="$style['required']">*</span></label>
              <input type="text" id="employee-lastname" v-model="newEmployee.lastName" :class="$style['input']" required :disabled="isLoading"/>
            </div>
          </div>
           <div :class="$style['grid-layout']">
              <div :class="$style['form-group']">
                <label for="employee-birthdate">Geburtsdatum <span :class="$style['required']">*</span></label>
                <input type="date" id="employee-birthdate" v-model="newEmployee.birthDate" :class="$style['input']" required :disabled="isLoading"/>
              </div>
              <div :class="$style['form-group']">
                <label for="employee-email">E-Mail <span :class="$style['required']">*</span></label>
                <input type="email" id="employee-email" v-model="newEmployee.email" :class="$style['input']" required :disabled="isLoading"/>
              </div>
           </div>
          <div :class="$style['form-group']">
            <label for="employee-password">Passwort <span :class="$style['required']">*</span></label>
            <input type="password" id="employee-password" v-model="newEmployee.password" :class="$style['input']" required :disabled="isLoading"/>
            <small>Mindestens 8 Zeichen.</small>
          </div>

          <hr :class="$style['divider']">

          <!-- Address Info -->
          <h3 :class="$style['section-title']">Adresse</h3>
           <div :class="$style['grid-layout']">
              <div :class="$style['form-group']">
                <label for="employee-zipcode">PLZ <span :class="$style['required']">*</span></label>
                <input type="number" id="employee-zipcode" v-model.number="newEmployee.address.zipcode" :class="$style['input']" required :disabled="isLoading"/>
              </div>
              <div :class="$style['form-group']">
                <label for="employee-city">Stadt <span :class="$style['required']">*</span></label>
                <input type="text" id="employee-city" v-model="newEmployee.address.city" :class="$style['input']" required :disabled="isLoading"/>
              </div>
           </div>
           <div :class="$style['grid-layout']">
              <div :class="$style['form-group']">
                <label for="employee-street">Straße <span :class="$style['required']">*</span></label>
                <input type="text" id="employee-street" v-model="newEmployee.address.street" :class="$style['input']" required :disabled="isLoading"/>
              </div>
              <div :class="$style['form-group']">
                <label for="employee-streetnumber">Hausnr. <span :class="$style['required']">*</span></label>
                <input type="text" id="employee-streetnumber" v-model="newEmployee.address.streetNumber" :class="$style['input']" required :disabled="isLoading"/>
              </div>
              <div :class="$style['form-group']">
                <label for="employee-apartment">Zusatz (Optional)</label>
                <input type="text" id="employee-apartment" v-model="newEmployee.address.apartment" :class="$style['input']" :disabled="isLoading"/>
              </div>
           </div>

          <hr :class="$style['divider']">

          <!-- Tax & Social Security Info -->
          <h3 :class="$style['section-title']">Steuer & Sozialversicherung</h3>
           <div :class="$style['grid-layout']">
              <div :class="$style['form-group']">
                <label for="employee-taxid">Steuer-ID <span :class="$style['required']">*</span></label>
                <input type="number" id="employee-taxid" v-model.number="newEmployee.taxId" :class="$style['input']" required :disabled="isLoading"/>
              </div>
              <div :class="$style['form-group']">
                <label for="employee-socialsecurityid">Sozialversicherungsnummer <span :class="$style['required']">*</span></label>
                <input type="text" id="employee-socialsecurityid" v-model="newEmployee.socialSecurityId" :class="$style['input']" required :disabled="isLoading"/>
              </div>
           </div>

          <hr :class="$style['divider']">

          <!-- Employment Info -->
          <h3 :class="$style['section-title']">Anstellung</h3>
          <div :class="$style['grid-layout']">
            <div :class="[$style['form-group'], $style['checkbox-group']]">
              <label for="employee-minijob">
                <input type="checkbox" id="employee-minijob" v-model="newEmployee.minijob" :class="$style['checkbox-inline']" :disabled="isLoading"/>
                <span :class="$style['checkbox-custom']"></span>
                <span :class="$style['checkbox-text']">Minijob</span>
              </label>
            </div>
            <div :class="$style['form-group']">
              <label for="employee-hourlywage">Stundenlohn (€)</label>
              <input type="number" step="0.01" id="employee-hourlywage" v-model.number="newEmployee.hourlyWage" :class="$style['input']" :disabled="isLoading || newEmployee.minijob" :required="!newEmployee.minijob"/>
              <small v-if="newEmployee.minijob">Nicht relevant für Minijob.</small>
            </div>
          </div>

          <!-- Messages -->
          <div v-if="errorMessage" :class="$style['error-message']">
            {{ errorMessage }}
          </div>
           <div v-if="successMessage" :class="$style['success-message']">
            {{ successMessage }}
          </div>

          <!-- Submit Button -->
          <button type="submit" :class="$style['create-button']" :disabled="isLoading">
            <FontAwesomeIcon v-if="isLoading" icon="spinner" spin :class="$style['button-icon']"/>
            <FontAwesomeIcon v-else icon="check" :class="$style['button-icon']"/>
            {{ isLoading ? 'Wird erstellt...' : 'Mitarbeiter erstellen' }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<style module lang="scss">
$bg-dark: #121212;
$bg-medium: #1e1e1e;
$bg-light: #2a2a2a;
$text-color: #f1f1f1;
$text-color-light: #b0b0b0;
$accent: #ff4500; // Red accent
$accent-hover: #b83200; // Darker red for hover
$border-radius: 6px;
$transition-speed: 0.2s;
$input-bg: #333;
$input-border: #555;
$input-focus-border: $accent;
$required-color: $accent;
$error-color: $accent;
$success-color: #2ecc71; // Green
$checkbox-size: 18px;

// --- Scrollbar ---
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-track {
  background: $bg-light;
  border-radius: 4px;
}
::-webkit-scrollbar-thumb {
  background-color: #555;
  border-radius: 4px;
  border: 2px solid $bg-light;
}
::-webkit-scrollbar-thumb:hover {
  background-color: #777;
}


.modal-overlay {
  position: fixed;
  inset: 0;
  background-color: rgba(0, 0, 0, 0.75);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1001; // Ensure it's above settings menu if needed
  padding: 20px;
}

.modal-content {
  background-color: $bg-medium;
  border-radius: $border-radius;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
  padding: 0;
  width: 100%;
  max-width: 750px; // Increased width slightly more
  position: relative;
  display: flex;
  flex-direction: column;
  max-height: 90vh;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 18px 25px;
  border-bottom: 1px solid $bg-light;
  flex-shrink: 0; // Prevent header from shrinking

  h2 {
    color: $text-color;
    font-size: 1.4rem;
    font-weight: 600;
    margin: 0;
  }

  .close-button {
    background: none;
    border: none;
    color: $text-color-light;
    cursor: pointer;
    font-size: 1.6rem;
    padding: 5px;
    line-height: 1;
    transition: color $transition-speed ease;

    &:hover {
      color: $text-color;
    }
  }
}

.modal-body {
  padding: 25px;
  overflow-y: auto; // Enable scrolling
  display: flex;
  flex-direction: column;
  gap: 20px; // Gap between sections/elements

  .section-title {
      font-size: 1.1rem;
      font-weight: 600;
      color: $text-color;
      margin-bottom: 10px; // Space below title
      padding-bottom: 5px;
      border-bottom: 1px solid $bg-light; // Subtle separator
  }

  .grid-layout {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); // Responsive grid
      gap: 15px 20px; // Row and column gap
      margin-bottom: 10px; // Space below grid
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 8px;

    label {
      color: $text-color;
      font-size: 0.9rem;
      font-weight: 500;
    }

    .required {
      color: $required-color;
      margin-left: 2px;
    }

    .input {
      width: 100%;
      padding: 10px 12px;
      border: 1px solid $input-border;
      border-radius: $border-radius;
      background-color: $input-bg;
      color: $text-color;
      box-sizing: border-box;
      font-size: 0.95rem;
      transition: border-color $transition-speed ease, box-shadow $transition-speed ease;

      &:focus {
        border-color: $input-focus-border;
        outline: none;
        box-shadow: 0 0 0 2px rgba($input-focus-border, 0.3);
      }
      &:disabled {
          background-color: darken($input-bg, 5%);
          cursor: not-allowed;
          opacity: 0.7;
      }
      // Remove spinners for number input
      &[type=number] {
        -moz-appearance: textfield;
        &::-webkit-outer-spin-button,
        &::-webkit-inner-spin-button {
          -webkit-appearance: none;
          margin: 0;
        }
      }
      // Style date input icon
      &[type="date"]::-webkit-calendar-picker-indicator {
          filter: invert(0.7); // Try to make the icon lighter on dark background
          cursor: pointer;
      }
    }
     small {
        font-size: 0.8rem;
        color: $text-color-light;
        line-height: 1.3;
     }
  }

  .checkbox-group {
      align-items: center; // Vertically align checkbox with label if needed
      padding-top: 20px; // Align with other inputs' labels roughly

      label {
          display: inline-flex; // Use inline-flex for alignment
          align-items: center;
          gap: 8px; // Gap between custom checkbox and text
          cursor: pointer;
          color: $text-color;
          font-size: 0.9rem;
          position: relative; // Needed for absolute positioning of ::before/::after
      }

      // Hide the default checkbox visually but keep it accessible
      .checkbox-inline {
           position: absolute;
           opacity: 0;
           cursor: pointer;
           height: 0;
           width: 0;
      }

      // The custom checkbox box
      .checkbox-custom {
          display: inline-block;
          width: $checkbox-size;
          height: $checkbox-size;
          background-color: $input-bg;
          border: 1px solid $input-border;
          border-radius: 4px;
          transition: background-color $transition-speed ease, border-color $transition-speed ease;
          position: relative; // For checkmark positioning
          flex-shrink: 0; // Prevent shrinking
      }

      // Style the custom checkbox when the hidden input is focused (for accessibility)
      .checkbox-inline:focus + .checkbox-custom {
          outline: none;
          box-shadow: 0 0 0 2px rgba($input-focus-border, 0.4);
          border-color: $input-focus-border;
      }

      // Style the custom checkbox when checked
      .checkbox-inline:checked + .checkbox-custom {
          background-color: $accent;
          border-color: $accent;
      }

      // The checkmark using ::after pseudo-element
      .checkbox-custom::after {
          content: "";
          position: absolute;
          display: none; // Hidden by default
          left: 5px; // Position checkmark
          top: 1px; // Position checkmark
          width: 5px;
          height: 10px;
          border: solid white;
          border-width: 0 2px 2px 0;
          transform: rotate(45deg);
      }

      // Show the checkmark when checked
      .checkbox-inline:checked + .checkbox-custom::after {
          display: block;
      }

      .checkbox-text {
          user-select: none;
      }
  }


  .divider {
      border: none;
      height: 1px;
      background-color: $bg-light;
      margin: 10px 0; // Space around divider
  }

  .error-message, .success-message {
    border-radius: $border-radius;
    padding: 10px 15px;
    font-size: 0.9rem;
    margin-top: 5px;
    text-align: center;
  }
  .error-message {
    color: $error-color;
    background-color: rgba($error-color, 0.1);
    border: 1px solid rgba($error-color, 0.3);
  }
  .success-message {
    color: $success-color;
    background-color: rgba($success-color, 0.1);
    border: 1px solid rgba($success-color, 0.3);
  }

  .create-button {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    padding: 12px 25px;
    background-color: $accent;
    color: $text-color;
    border: none;
    border-radius: $border-radius;
    cursor: pointer;
    transition: background-color $transition-speed ease, transform 0.1s ease;
    width: 100%;
    margin-top: 15px;
    font-size: 1rem;
    font-weight: 600;

    &:hover:not(:disabled) {
      background-color: $accent-hover;
    }
    &:active:not(:disabled) {
      transform: scale(0.98);
    }
    &:disabled {
        background-color: darken($accent, 20%);
        cursor: not-allowed;
    }

    .button-icon {
      font-size: 0.9em;
    }
  }
}
</style>
